"""Minimal entry point to regenerate statistics.yaml without re-running MuJoCo.

Usage (recompute stats from existing data.jsonl):
    python tools/preprocess/run_libero_preprocess.py --stats-only \
        --output-dir datasets/uamvla_test/libero_spatial

Usage (full preprocessing from source HDF5):
    python tools/preprocess/run_libero_preprocess.py \
        --input-dir dataset/libero2uam/raw/libero_spatial_test \
        --output-dir datasets/uamvla_test/libero_spatial

Environment variables:
    LIBERO_INPUT_DIR   source HDF5 directory (overridden by --input-dir)
    LIBERO_OUTPUT_DIR  output directory      (overridden by --output-dir)
"""
import argparse
import json
import logging
import os
import sys
from pathlib import Path

import yaml

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

# Make project root importable when invoked as a script
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.preprocess.libero_preprocessor import (  # noqa: E402
    LiberoPreprocessor,
    STATIC_CAM,
    WRIST_CAM,
)


def parse_args():
    p = argparse.ArgumentParser(description="Preprocess LIBERO data to UamVLA format")
    p.add_argument(
        "--input-dir",
        default=os.environ.get("LIBERO_INPUT_DIR", ""),
        help="Directory containing source .hdf5 files",
    )
    p.add_argument(
        "--output-dir",
        default=os.environ.get("LIBERO_OUTPUT_DIR", None),
        help="Output directory for UamVLA dataset (required)",
    )
    p.add_argument(
        "--suite",
        default="libero_spatial",
        help="Suite name embedded in sample IDs (default: libero_spatial)",
    )
    p.add_argument(
        "--stats-only",
        action="store_true",
        help=(
            "Skip MuJoCo replay; recompute statistics.yaml only from the "
            "existing data.jsonl in --output-dir.  Requires the output-dir "
            "to already contain data.jsonl and a statistics.yaml with camera "
            "intrinsics (used as the canonical camera parameters)."
        ),
    )
    return p, p.parse_args()


def recompute_stats_only(output_dir: Path, suite: str):
    """Recompute statistics.yaml from existing data.jsonl without MuJoCo."""
    jsonl_path = output_dir / "data.jsonl"
    stats_path = output_dir / "statistics.yaml"

    if not jsonl_path.exists():
        raise FileNotFoundError(f"data.jsonl not found in {output_dir}")
    if not stats_path.exists():
        raise FileNotFoundError(
            f"statistics.yaml not found in {output_dir} — "
            f"need it to read camera intrinsics"
        )

    # Load samples
    samples = []
    with open(jsonl_path) as f:
        for line in f:
            line = line.strip()
            if line:
                samples.append(json.loads(line))
    logging.info(f"Loaded {len(samples)} samples from {jsonl_path}")

    # Carry over camera_intrinsics from the existing yaml.
    # WARNING: these values are passed through verbatim — no recomputation.
    with open(stats_path) as f:
        old_stats = yaml.safe_load(f)
    camera_intrinsics = {
        STATIC_CAM: old_stats["cameras"]["static"]["intrinsic"],
        WRIST_CAM: old_stats["cameras"]["wrist"]["intrinsic"],
    }
    logging.warning(
        "[--stats-only] Camera intrinsics carried over verbatim from existing %s. "
        "If the previous yaml was generated by a stale or buggy preprocessor, "
        "these values may be wrong. Re-run full preprocessing if intrinsics need refreshing.",
        stats_path,
    )

    # Basic sanity check on intrinsics to catch corrupted / partially-written yaml.
    for cam_key, intrinsics in camera_intrinsics.items():
        if isinstance(intrinsics, dict):
            fx = intrinsics.get("fx", 0)
            fy = intrinsics.get("fy", 0)
            cx = intrinsics.get("cx", 0)
            cy = intrinsics.get("cy", 0)
            width = intrinsics.get("width", 0)
            height = intrinsics.get("height", 0)
        elif isinstance(intrinsics, list):
            # 3×3 matrix stored flat: [fx, 0, cx, 0, fy, cy, 0, 0, 1]
            if len(intrinsics) == 9:
                fx, fy = intrinsics[0], intrinsics[4]
                cx, cy = intrinsics[2], intrinsics[5]
                width = cx * 2  # approximate — flat list has no explicit W/H
                height = cy * 2
            else:
                raise ValueError(
                    f"Invalid camera intrinsics in {stats_path} for '{cam_key}': "
                    f"expected 9-element flat list, got {len(intrinsics)} elements"
                )
        else:
            raise ValueError(
                f"Invalid camera intrinsics in {stats_path} for '{cam_key}': "
                f"unexpected type {type(intrinsics)}"
            )
        if not (fx > 0 and fy > 0 and cx > 0 and cy > 0):
            raise ValueError(
                f"Invalid camera intrinsics in {stats_path} for '{cam_key}': {intrinsics}"
            )

    preprocessor = LiberoPreprocessor(suite=suite)
    preprocessor.write_statistics(samples, output_dir, camera_intrinsics)
    logging.info("statistics.yaml rewritten with new schema")


def main():
    parser, args = parse_args()

    if args.output_dir is None:
        parser.error(
            "--output-dir is required "
            "(use 'datasets/uamvla_test/libero_spatial' for the project test fixture)"
        )

    output_dir = Path(args.output_dir)

    if args.stats_only:
        recompute_stats_only(output_dir, args.suite)
        return

    if not args.input_dir:
        print(
            "ERROR: --input-dir (or LIBERO_INPUT_DIR) is required for full preprocessing.",
            file=sys.stderr,
        )
        sys.exit(1)

    preprocessor = LiberoPreprocessor(suite=args.suite)
    preprocessor.process(args.input_dir, str(output_dir))


if __name__ == "__main__":
    main()
